export const enum CM_CARDPATTERN {
    CP_NIU0 = 0,
    CP_NIU1,
    CP_NIU2,
    CP_NIU3,
    CP_NIU4,
    CP_NIU5,
    CP_NIU6,
    CP_NIU7,
    CP_NIU8,
    CP_NIU9,

    CP_NIUNIU,

    CP_HULU,		// 葫芦牛
    CP_SHUNZI,		// 顺子牛
    CP_TONGHUA,		// 同花牛
    CP_YINNIU,		// 银牛
    CP_ZHADAN,		// 炸弹牛
    CP_TONGHUASHUN,	// 同花顺
    CP_5XIAONIU,	// 5小牛
    CP_5HUANIU,	    // 5花牛
};

export const CM_PATTERN_NAME: any = {};
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU0] = "无牛"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU1] = "牛丁"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU2] = "牛二"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU3] = "牛三"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU4] = "牛四"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU5] = "牛五"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU6] = "牛六"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU7] = "牛七"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU8] = "牛八"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIU9] = "牛九"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_NIUNIU] = "牛牛"
CM_PATTERN_NAME[CM_CARDPATTERN.CP_HULU] = "葫芦牛"		// 葫芦牛
CM_PATTERN_NAME[CM_CARDPATTERN.CP_SHUNZI] = "顺子牛"		// 顺子牛
CM_PATTERN_NAME[CM_CARDPATTERN.CP_TONGHUA] = "同花牛"		// 同花牛
CM_PATTERN_NAME[CM_CARDPATTERN.CP_YINNIU] = "银牛"		// 银牛
CM_PATTERN_NAME[CM_CARDPATTERN.CP_ZHADAN] = "炸弹牛"		// 炸弹牛
CM_PATTERN_NAME[CM_CARDPATTERN.CP_TONGHUASHUN] = "同花顺"	// 同花顺
CM_PATTERN_NAME[CM_CARDPATTERN.CP_5XIAONIU] = "5小牛"	// 5小牛
CM_PATTERN_NAME[CM_CARDPATTERN.CP_5HUANIU] = "5花牛"	    // 5花牛