// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

"use strict;"

var assert     = require('assert');
var TarsStream = require('@tars/stream');


var CocklainStruct = CocklainStruct || {};
module.exports.CocklainStruct = CocklainStruct;

CocklainStruct.E_CLIENT_MSG = {
    CM_Snatchbanker : 100,
    CM_ChooseBaseScore : 101,
    CM_SellScore : 102,
    CM_BuyScore : 103,
    CM_GetGameData : 104,
    CM_UserHead : 105
};
CocklainStruct.E_CLIENT_MSG._write = function(os, tag, val) { return os.writeInt32(tag, val); }
CocklainStruct.E_CLIENT_MSG._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
CocklainStruct.E_SERVER_MSG = {
    SM_SendCard : 200,
    SM_Snatchbanker : 201,
    SM_SnatchbankerFinish : 202,
    SM_ChooseBaseScore : 203,
    SM_CM_ChooseBaseScore : 204,
    SM_ChooseBaseScoreFinish : 205,
    SM_ScoreSellBuy : 206,
    SM_ScoreSellBuyRecord : 207,
    SM_SendLastCard : 208,
    SM_RoundEnd : 209,
    SM_GameEnd : 210,
    SM_GameData : 211
};
CocklainStruct.E_SERVER_MSG._write = function(os, tag, val) { return os.writeInt32(tag, val); }
CocklainStruct.E_SERVER_MSG._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
CocklainStruct.E_CARD_PATTERN = {
    CP_Niu0 : 100,
    CP_Niu1 : 101,
    CP_Niu2 : 102,
    CP_Niu3 : 103,
    CP_Niu4 : 104,
    CP_Niu5 : 105,
    CP_Niu6 : 106,
    CP_Niu7 : 107,
    CP_Niu8 : 108,
    CP_Niu9 : 109,
    CP_Niuniu : 110,
    CP_Hulu : 111,
    CP_Shunzi : 112,
    CP_Tonghua : 113,
    CP_YinNiu : 114,
    CP_Zhadan : 115,
    CP_Tonghuashun : 116,
    CP_5XiaoNiu : 117,
    CP_5HuaNiu : 118
};
CocklainStruct.E_CARD_PATTERN._write = function(os, tag, val) { return os.writeInt32(tag, val); }
CocklainStruct.E_CARD_PATTERN._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
CocklainStruct.E_GAME_STATUS = {
    GS_SendCard : 10,
    GS_Snatchbanker : 11,
    GS_ChooseBaseScore : 12,
    GS_ScoreSellBuy : 13,
    GS_SendLastCard : 14,
    GS_RoundEnd : 15
};
CocklainStruct.E_GAME_STATUS._write = function(os, tag, val) { return os.writeInt32(tag, val); }
CocklainStruct.E_GAME_STATUS._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

CocklainStruct.TIntMsg = function() {
    this.iValue = 0;
    this._classname = "CocklainStruct.TIntMsg";
};
CocklainStruct.TIntMsg._classname = "CocklainStruct.TIntMsg";

CocklainStruct.TIntMsg._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TIntMsg._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TIntMsg._readFrom = function (is) {
    var tmp = new CocklainStruct.TIntMsg();
    tmp.iValue = is.readInt32(0, true, 0);
    return tmp;
};
CocklainStruct.TIntMsg.prototype._writeTo = function (os) {
    os.writeInt32(0, this.iValue);
};
CocklainStruct.TIntMsg.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TIntMsg.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TIntMsg.prototype.toObject = function() { 
    var tmp = {};

    tmp.iValue = this.iValue;
    
    return tmp;
}
CocklainStruct.TIntMsg.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iValue") || (this.iValue = json.iValue);
}
CocklainStruct.TIntMsg.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TIntMsg.new = function () {
    return new CocklainStruct.TIntMsg();
}
CocklainStruct.TIntMsg.create = function (is) {
    return CocklainStruct.TIntMsg._readFrom(is);
}
CocklainStruct.TUserHead = function() {
    this.strNickname = "";
    this.strHeadImgURL = "";
    this._classname = "CocklainStruct.TUserHead";
};
CocklainStruct.TUserHead._classname = "CocklainStruct.TUserHead";

CocklainStruct.TUserHead._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserHead._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserHead._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserHead();
    tmp.strNickname = is.readString(0, true, "");
    tmp.strHeadImgURL = is.readString(1, true, "");
    return tmp;
};
CocklainStruct.TUserHead.prototype._writeTo = function (os) {
    os.writeString(0, this.strNickname);
    os.writeString(1, this.strHeadImgURL);
};
CocklainStruct.TUserHead.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserHead.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserHead.prototype.toObject = function() { 
    var tmp = {};

    tmp.strNickname = this.strNickname;
    tmp.strHeadImgURL = this.strHeadImgURL;
    
    return tmp;
}
CocklainStruct.TUserHead.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("strNickname") || (this.strNickname = json.strNickname);
    !json.hasOwnProperty("strHeadImgURL") || (this.strHeadImgURL = json.strHeadImgURL);
}
CocklainStruct.TUserHead.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserHead.new = function () {
    return new CocklainStruct.TUserHead();
}
CocklainStruct.TUserHead.create = function (is) {
    return CocklainStruct.TUserHead._readFrom(is);
}
CocklainStruct.TUserCard = function() {
    this.vecCards = new TarsStream.List(TarsStream.Int64);
    this._classname = "CocklainStruct.TUserCard";
};
CocklainStruct.TUserCard._classname = "CocklainStruct.TUserCard";

CocklainStruct.TUserCard._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserCard._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserCard._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserCard();
    tmp.vecCards = is.readList(0, true, TarsStream.List(TarsStream.Int64));
    return tmp;
};
CocklainStruct.TUserCard.prototype._writeTo = function (os) {
    os.writeList(0, this.vecCards);
};
CocklainStruct.TUserCard.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserCard.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserCard.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecCards = this.vecCards.toObject();
    
    return tmp;
}
CocklainStruct.TUserCard.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecCards") || (this.vecCards.readFromObject(json.vecCards));
}
CocklainStruct.TUserCard.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserCard.new = function () {
    return new CocklainStruct.TUserCard();
}
CocklainStruct.TUserCard.create = function (is) {
    return CocklainStruct.TUserCard._readFrom(is);
}
CocklainStruct.TSendCardData = function() {
    this.vecUserCards = new TarsStream.List(CocklainStruct.TUserCard);
    this.uiCurrRound = 0;
    this._classname = "CocklainStruct.TSendCardData";
};
CocklainStruct.TSendCardData._classname = "CocklainStruct.TSendCardData";

CocklainStruct.TSendCardData._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TSendCardData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TSendCardData._readFrom = function (is) {
    var tmp = new CocklainStruct.TSendCardData();
    tmp.vecUserCards = is.readList(0, true, TarsStream.List(CocklainStruct.TUserCard));
    tmp.uiCurrRound = is.readUInt32(1, true, 0);
    return tmp;
};
CocklainStruct.TSendCardData.prototype._writeTo = function (os) {
    os.writeList(0, this.vecUserCards);
    os.writeUInt32(1, this.uiCurrRound);
};
CocklainStruct.TSendCardData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TSendCardData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TSendCardData.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecUserCards = this.vecUserCards.toObject();
    tmp.uiCurrRound = this.uiCurrRound;
    
    return tmp;
}
CocklainStruct.TSendCardData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecUserCards") || (this.vecUserCards.readFromObject(json.vecUserCards));
    !json.hasOwnProperty("uiCurrRound") || (this.uiCurrRound = json.uiCurrRound);
}
CocklainStruct.TSendCardData.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TSendCardData.new = function () {
    return new CocklainStruct.TSendCardData();
}
CocklainStruct.TSendCardData.create = function (is) {
    return CocklainStruct.TSendCardData._readFrom(is);
}
CocklainStruct.TUserSnatchbankerMultiple = function() {
    this.uiChairIndex = 0;
    this.uiMultiple = 0;
    this._classname = "CocklainStruct.TUserSnatchbankerMultiple";
};
CocklainStruct.TUserSnatchbankerMultiple._classname = "CocklainStruct.TUserSnatchbankerMultiple";

CocklainStruct.TUserSnatchbankerMultiple._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserSnatchbankerMultiple._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserSnatchbankerMultiple._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserSnatchbankerMultiple();
    tmp.uiChairIndex = is.readUInt32(0, false, 0);
    tmp.uiMultiple = is.readUInt32(2, true, 0);
    return tmp;
};
CocklainStruct.TUserSnatchbankerMultiple.prototype._writeTo = function (os) {
    os.writeUInt32(0, this.uiChairIndex);
    os.writeUInt32(2, this.uiMultiple);
};
CocklainStruct.TUserSnatchbankerMultiple.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserSnatchbankerMultiple.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserSnatchbankerMultiple.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiChairIndex = this.uiChairIndex;
    tmp.uiMultiple = this.uiMultiple;
    
    return tmp;
}
CocklainStruct.TUserSnatchbankerMultiple.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiChairIndex") || (this.uiChairIndex = json.uiChairIndex);
    !json.hasOwnProperty("uiMultiple") || (this.uiMultiple = json.uiMultiple);
}
CocklainStruct.TUserSnatchbankerMultiple.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserSnatchbankerMultiple.new = function () {
    return new CocklainStruct.TUserSnatchbankerMultiple();
}
CocklainStruct.TUserSnatchbankerMultiple.create = function (is) {
    return CocklainStruct.TUserSnatchbankerMultiple._readFrom(is);
}
CocklainStruct.TUserBolusConf = function() {
    this.uiChairIndex = 0;
    this.uiBolus = 0;
    this._classname = "CocklainStruct.TUserBolusConf";
};
CocklainStruct.TUserBolusConf._classname = "CocklainStruct.TUserBolusConf";

CocklainStruct.TUserBolusConf._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserBolusConf._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserBolusConf._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserBolusConf();
    tmp.uiChairIndex = is.readUInt32(0, true, 0);
    tmp.uiBolus = is.readUInt32(1, true, 0);
    return tmp;
};
CocklainStruct.TUserBolusConf.prototype._writeTo = function (os) {
    os.writeUInt32(0, this.uiChairIndex);
    os.writeUInt32(1, this.uiBolus);
};
CocklainStruct.TUserBolusConf.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserBolusConf.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserBolusConf.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiChairIndex = this.uiChairIndex;
    tmp.uiBolus = this.uiBolus;
    
    return tmp;
}
CocklainStruct.TUserBolusConf.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiChairIndex") || (this.uiChairIndex = json.uiChairIndex);
    !json.hasOwnProperty("uiBolus") || (this.uiBolus = json.uiBolus);
}
CocklainStruct.TUserBolusConf.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserBolusConf.new = function () {
    return new CocklainStruct.TUserBolusConf();
}
CocklainStruct.TUserBolusConf.create = function (is) {
    return CocklainStruct.TUserBolusConf._readFrom(is);
}
CocklainStruct.TBaseScoreConf = function() {
    this.uiBaseScore1 = 0;
    this.uiBaseScore2 = 0;
    this.vecUserBolusConf = new TarsStream.List(CocklainStruct.TUserBolusConf);
    this._classname = "CocklainStruct.TBaseScoreConf";
};
CocklainStruct.TBaseScoreConf._classname = "CocklainStruct.TBaseScoreConf";

CocklainStruct.TBaseScoreConf._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TBaseScoreConf._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TBaseScoreConf._readFrom = function (is) {
    var tmp = new CocklainStruct.TBaseScoreConf();
    tmp.uiBaseScore1 = is.readUInt32(0, true, 0);
    tmp.uiBaseScore2 = is.readUInt32(1, true, 0);
    tmp.vecUserBolusConf = is.readList(2, true, TarsStream.List(CocklainStruct.TUserBolusConf));
    return tmp;
};
CocklainStruct.TBaseScoreConf.prototype._writeTo = function (os) {
    os.writeUInt32(0, this.uiBaseScore1);
    os.writeUInt32(1, this.uiBaseScore2);
    os.writeList(2, this.vecUserBolusConf);
};
CocklainStruct.TBaseScoreConf.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TBaseScoreConf.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TBaseScoreConf.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiBaseScore1 = this.uiBaseScore1;
    tmp.uiBaseScore2 = this.uiBaseScore2;
    tmp.vecUserBolusConf = this.vecUserBolusConf.toObject();
    
    return tmp;
}
CocklainStruct.TBaseScoreConf.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiBaseScore1") || (this.uiBaseScore1 = json.uiBaseScore1);
    !json.hasOwnProperty("uiBaseScore2") || (this.uiBaseScore2 = json.uiBaseScore2);
    !json.hasOwnProperty("vecUserBolusConf") || (this.vecUserBolusConf.readFromObject(json.vecUserBolusConf));
}
CocklainStruct.TBaseScoreConf.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TBaseScoreConf.new = function () {
    return new CocklainStruct.TBaseScoreConf();
}
CocklainStruct.TBaseScoreConf.create = function (is) {
    return CocklainStruct.TBaseScoreConf._readFrom(is);
}
CocklainStruct.TUserChooseBaseScore = function() {
    this.uiChairIndex = 0;
    this.uiBaseScore = 0;
    this._classname = "CocklainStruct.TUserChooseBaseScore";
};
CocklainStruct.TUserChooseBaseScore._classname = "CocklainStruct.TUserChooseBaseScore";

CocklainStruct.TUserChooseBaseScore._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserChooseBaseScore._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserChooseBaseScore._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserChooseBaseScore();
    tmp.uiChairIndex = is.readUInt32(0, false, 0);
    tmp.uiBaseScore = is.readUInt32(1, true, 0);
    return tmp;
};
CocklainStruct.TUserChooseBaseScore.prototype._writeTo = function (os) {
    os.writeUInt32(0, this.uiChairIndex);
    os.writeUInt32(1, this.uiBaseScore);
};
CocklainStruct.TUserChooseBaseScore.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserChooseBaseScore.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserChooseBaseScore.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiChairIndex = this.uiChairIndex;
    tmp.uiBaseScore = this.uiBaseScore;
    
    return tmp;
}
CocklainStruct.TUserChooseBaseScore.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiChairIndex") || (this.uiChairIndex = json.uiChairIndex);
    !json.hasOwnProperty("uiBaseScore") || (this.uiBaseScore = json.uiBaseScore);
}
CocklainStruct.TUserChooseBaseScore.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserChooseBaseScore.new = function () {
    return new CocklainStruct.TUserChooseBaseScore();
}
CocklainStruct.TUserChooseBaseScore.create = function (is) {
    return CocklainStruct.TUserChooseBaseScore._readFrom(is);
}
CocklainStruct.TUserChooseBaseScoreRecord = function() {
    this.vecUserBaseScore = new TarsStream.List(CocklainStruct.TUserChooseBaseScore);
    this._classname = "CocklainStruct.TUserChooseBaseScoreRecord";
};
CocklainStruct.TUserChooseBaseScoreRecord._classname = "CocklainStruct.TUserChooseBaseScoreRecord";

CocklainStruct.TUserChooseBaseScoreRecord._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserChooseBaseScoreRecord._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserChooseBaseScoreRecord._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserChooseBaseScoreRecord();
    tmp.vecUserBaseScore = is.readList(0, true, TarsStream.List(CocklainStruct.TUserChooseBaseScore));
    return tmp;
};
CocklainStruct.TUserChooseBaseScoreRecord.prototype._writeTo = function (os) {
    os.writeList(0, this.vecUserBaseScore);
};
CocklainStruct.TUserChooseBaseScoreRecord.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserChooseBaseScoreRecord.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserChooseBaseScoreRecord.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecUserBaseScore = this.vecUserBaseScore.toObject();
    
    return tmp;
}
CocklainStruct.TUserChooseBaseScoreRecord.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecUserBaseScore") || (this.vecUserBaseScore.readFromObject(json.vecUserBaseScore));
}
CocklainStruct.TUserChooseBaseScoreRecord.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserChooseBaseScoreRecord.new = function () {
    return new CocklainStruct.TUserChooseBaseScoreRecord();
}
CocklainStruct.TUserChooseBaseScoreRecord.create = function (is) {
    return CocklainStruct.TUserChooseBaseScoreRecord._readFrom(is);
}
CocklainStruct.TScoreSellBuyConf = function() {
    this.vecSellBuyScores = new TarsStream.List(TarsStream.Int64);
    this._classname = "CocklainStruct.TScoreSellBuyConf";
};
CocklainStruct.TScoreSellBuyConf._classname = "CocklainStruct.TScoreSellBuyConf";

CocklainStruct.TScoreSellBuyConf._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TScoreSellBuyConf._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TScoreSellBuyConf._readFrom = function (is) {
    var tmp = new CocklainStruct.TScoreSellBuyConf();
    tmp.vecSellBuyScores = is.readList(0, true, TarsStream.List(TarsStream.Int64));
    return tmp;
};
CocklainStruct.TScoreSellBuyConf.prototype._writeTo = function (os) {
    os.writeList(0, this.vecSellBuyScores);
};
CocklainStruct.TScoreSellBuyConf.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TScoreSellBuyConf.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TScoreSellBuyConf.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecSellBuyScores = this.vecSellBuyScores.toObject();
    
    return tmp;
}
CocklainStruct.TScoreSellBuyConf.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecSellBuyScores") || (this.vecSellBuyScores.readFromObject(json.vecSellBuyScores));
}
CocklainStruct.TScoreSellBuyConf.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TScoreSellBuyConf.new = function () {
    return new CocklainStruct.TScoreSellBuyConf();
}
CocklainStruct.TScoreSellBuyConf.create = function (is) {
    return CocklainStruct.TScoreSellBuyConf._readFrom(is);
}
CocklainStruct.TUserScoreSellBuy = function() {
    this.uiChairIndex = 0;
    this.uiSellScore = 0;
    this.bSelled = true;
    this.uiBuyedScore = 0;
    this._classname = "CocklainStruct.TUserScoreSellBuy";
};
CocklainStruct.TUserScoreSellBuy._classname = "CocklainStruct.TUserScoreSellBuy";

CocklainStruct.TUserScoreSellBuy._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserScoreSellBuy._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserScoreSellBuy._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserScoreSellBuy();
    tmp.uiChairIndex = is.readUInt32(0, true, 0);
    tmp.uiSellScore = is.readUInt32(1, true, 0);
    tmp.bSelled = is.readBoolean(2, true, true);
    tmp.uiBuyedScore = is.readUInt32(3, true, 0);
    return tmp;
};
CocklainStruct.TUserScoreSellBuy.prototype._writeTo = function (os) {
    os.writeUInt32(0, this.uiChairIndex);
    os.writeUInt32(1, this.uiSellScore);
    os.writeBoolean(2, this.bSelled);
    os.writeUInt32(3, this.uiBuyedScore);
};
CocklainStruct.TUserScoreSellBuy.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserScoreSellBuy.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserScoreSellBuy.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiChairIndex = this.uiChairIndex;
    tmp.uiSellScore = this.uiSellScore;
    tmp.bSelled = this.bSelled;
    tmp.uiBuyedScore = this.uiBuyedScore;
    
    return tmp;
}
CocklainStruct.TUserScoreSellBuy.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiChairIndex") || (this.uiChairIndex = json.uiChairIndex);
    !json.hasOwnProperty("uiSellScore") || (this.uiSellScore = json.uiSellScore);
    !json.hasOwnProperty("bSelled") || (this.bSelled = json.bSelled);
    !json.hasOwnProperty("uiBuyedScore") || (this.uiBuyedScore = json.uiBuyedScore);
}
CocklainStruct.TUserScoreSellBuy.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserScoreSellBuy.new = function () {
    return new CocklainStruct.TUserScoreSellBuy();
}
CocklainStruct.TUserScoreSellBuy.create = function (is) {
    return CocklainStruct.TUserScoreSellBuy._readFrom(is);
}
CocklainStruct.TScoreSellBuyRecord = function() {
    this.vecUserScoreSellBuy = new TarsStream.List(CocklainStruct.TUserScoreSellBuy);
    this._classname = "CocklainStruct.TScoreSellBuyRecord";
};
CocklainStruct.TScoreSellBuyRecord._classname = "CocklainStruct.TScoreSellBuyRecord";

CocklainStruct.TScoreSellBuyRecord._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TScoreSellBuyRecord._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TScoreSellBuyRecord._readFrom = function (is) {
    var tmp = new CocklainStruct.TScoreSellBuyRecord();
    tmp.vecUserScoreSellBuy = is.readList(0, true, TarsStream.List(CocklainStruct.TUserScoreSellBuy));
    return tmp;
};
CocklainStruct.TScoreSellBuyRecord.prototype._writeTo = function (os) {
    os.writeList(0, this.vecUserScoreSellBuy);
};
CocklainStruct.TScoreSellBuyRecord.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TScoreSellBuyRecord.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TScoreSellBuyRecord.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecUserScoreSellBuy = this.vecUserScoreSellBuy.toObject();
    
    return tmp;
}
CocklainStruct.TScoreSellBuyRecord.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecUserScoreSellBuy") || (this.vecUserScoreSellBuy.readFromObject(json.vecUserScoreSellBuy));
}
CocklainStruct.TScoreSellBuyRecord.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TScoreSellBuyRecord.new = function () {
    return new CocklainStruct.TScoreSellBuyRecord();
}
CocklainStruct.TScoreSellBuyRecord.create = function (is) {
    return CocklainStruct.TScoreSellBuyRecord._readFrom(is);
}
CocklainStruct.TUserRoundResult = function() {
    this.userCard = new CocklainStruct.TUserCard();
    this.eCardPattern = CocklainStruct.E_CARD_PATTERN.CP_Niu0;
    this.vecNiuCards = new TarsStream.List(TarsStream.Int64);
    this.iGainScore = 0;
    this.iRemainScore = 0;
    this.bBanker = true;
    this._classname = "CocklainStruct.TUserRoundResult";
};
CocklainStruct.TUserRoundResult._classname = "CocklainStruct.TUserRoundResult";

CocklainStruct.TUserRoundResult._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserRoundResult._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserRoundResult._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserRoundResult();
    tmp.userCard = is.readStruct(0, true, CocklainStruct.TUserCard);
    tmp.eCardPattern = is.readInt32(1, false, CocklainStruct.E_CARD_PATTERN.CP_Niu0);
    tmp.vecNiuCards = is.readList(2, false, TarsStream.List(TarsStream.Int64));
    tmp.iGainScore = is.readInt32(3, true, 0);
    tmp.iRemainScore = is.readInt32(4, true, 0);
    tmp.bBanker = is.readBoolean(5, true, true);
    return tmp;
};
CocklainStruct.TUserRoundResult.prototype._writeTo = function (os) {
    os.writeStruct(0, this.userCard);
    os.writeInt32(1, this.eCardPattern);
    os.writeList(2, this.vecNiuCards);
    os.writeInt32(3, this.iGainScore);
    os.writeInt32(4, this.iRemainScore);
    os.writeBoolean(5, this.bBanker);
};
CocklainStruct.TUserRoundResult.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserRoundResult.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserRoundResult.prototype.toObject = function() { 
    var tmp = {};

    tmp.userCard = this.userCard.toObject();
    tmp.eCardPattern = this.eCardPattern;
    tmp.vecNiuCards = this.vecNiuCards.toObject();
    tmp.iGainScore = this.iGainScore;
    tmp.iRemainScore = this.iRemainScore;
    tmp.bBanker = this.bBanker;
    
    return tmp;
}
CocklainStruct.TUserRoundResult.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("userCard") || (this.userCard.readFromObject(json.userCard));
    !json.hasOwnProperty("eCardPattern") || (this.eCardPattern = json.eCardPattern);
    !json.hasOwnProperty("vecNiuCards") || (this.vecNiuCards.readFromObject(json.vecNiuCards));
    !json.hasOwnProperty("iGainScore") || (this.iGainScore = json.iGainScore);
    !json.hasOwnProperty("iRemainScore") || (this.iRemainScore = json.iRemainScore);
    !json.hasOwnProperty("bBanker") || (this.bBanker = json.bBanker);
}
CocklainStruct.TUserRoundResult.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserRoundResult.new = function () {
    return new CocklainStruct.TUserRoundResult();
}
CocklainStruct.TUserRoundResult.create = function (is) {
    return CocklainStruct.TUserRoundResult._readFrom(is);
}
CocklainStruct.TRoundResult = function() {
    this.vecUserResult = new TarsStream.List(CocklainStruct.TUserRoundResult);
    this._classname = "CocklainStruct.TRoundResult";
};
CocklainStruct.TRoundResult._classname = "CocklainStruct.TRoundResult";

CocklainStruct.TRoundResult._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TRoundResult._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TRoundResult._readFrom = function (is) {
    var tmp = new CocklainStruct.TRoundResult();
    tmp.vecUserResult = is.readList(0, true, TarsStream.List(CocklainStruct.TUserRoundResult));
    return tmp;
};
CocklainStruct.TRoundResult.prototype._writeTo = function (os) {
    os.writeList(0, this.vecUserResult);
};
CocklainStruct.TRoundResult.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TRoundResult.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TRoundResult.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecUserResult = this.vecUserResult.toObject();
    
    return tmp;
}
CocklainStruct.TRoundResult.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecUserResult") || (this.vecUserResult.readFromObject(json.vecUserResult));
}
CocklainStruct.TRoundResult.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TRoundResult.new = function () {
    return new CocklainStruct.TRoundResult();
}
CocklainStruct.TRoundResult.create = function (is) {
    return CocklainStruct.TRoundResult._readFrom(is);
}
CocklainStruct.TUserGameResult = function() {
    this.uiUserID = 0;
    this.iRemainScore = 0;
    this.strNickname = "";
    this.strHeadImgURL = "";
    this._classname = "CocklainStruct.TUserGameResult";
};
CocklainStruct.TUserGameResult._classname = "CocklainStruct.TUserGameResult";

CocklainStruct.TUserGameResult._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserGameResult._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserGameResult._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserGameResult();
    tmp.uiUserID = is.readUInt32(0, true, 0);
    tmp.iRemainScore = is.readInt32(1, true, 0);
    tmp.strNickname = is.readString(2, true, "");
    tmp.strHeadImgURL = is.readString(3, true, "");
    return tmp;
};
CocklainStruct.TUserGameResult.prototype._writeTo = function (os) {
    os.writeUInt32(0, this.uiUserID);
    os.writeInt32(1, this.iRemainScore);
    os.writeString(2, this.strNickname);
    os.writeString(3, this.strHeadImgURL);
};
CocklainStruct.TUserGameResult.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserGameResult.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserGameResult.prototype.toObject = function() { 
    var tmp = {};

    tmp.uiUserID = this.uiUserID;
    tmp.iRemainScore = this.iRemainScore;
    tmp.strNickname = this.strNickname;
    tmp.strHeadImgURL = this.strHeadImgURL;
    
    return tmp;
}
CocklainStruct.TUserGameResult.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("uiUserID") || (this.uiUserID = json.uiUserID);
    !json.hasOwnProperty("iRemainScore") || (this.iRemainScore = json.iRemainScore);
    !json.hasOwnProperty("strNickname") || (this.strNickname = json.strNickname);
    !json.hasOwnProperty("strHeadImgURL") || (this.strHeadImgURL = json.strHeadImgURL);
}
CocklainStruct.TUserGameResult.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserGameResult.new = function () {
    return new CocklainStruct.TUserGameResult();
}
CocklainStruct.TUserGameResult.create = function (is) {
    return CocklainStruct.TUserGameResult._readFrom(is);
}
CocklainStruct.TGameResult = function() {
    this.vecUserGameResult = new TarsStream.List(CocklainStruct.TUserGameResult);
    this._classname = "CocklainStruct.TGameResult";
};
CocklainStruct.TGameResult._classname = "CocklainStruct.TGameResult";

CocklainStruct.TGameResult._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TGameResult._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TGameResult._readFrom = function (is) {
    var tmp = new CocklainStruct.TGameResult();
    tmp.vecUserGameResult = is.readList(0, true, TarsStream.List(CocklainStruct.TUserGameResult));
    return tmp;
};
CocklainStruct.TGameResult.prototype._writeTo = function (os) {
    os.writeList(0, this.vecUserGameResult);
};
CocklainStruct.TGameResult.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TGameResult.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TGameResult.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecUserGameResult = this.vecUserGameResult.toObject();
    
    return tmp;
}
CocklainStruct.TGameResult.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecUserGameResult") || (this.vecUserGameResult.readFromObject(json.vecUserGameResult));
}
CocklainStruct.TGameResult.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TGameResult.new = function () {
    return new CocklainStruct.TGameResult();
}
CocklainStruct.TGameResult.create = function (is) {
    return CocklainStruct.TGameResult._readFrom(is);
}
CocklainStruct.TUserDetail = function() {
    this.bBanker = true;
    this.uiSnatchbankerMutiple = 0;
    this.uiBaseScore = 0;
    this.iRemainScore = 0;
    this._classname = "CocklainStruct.TUserDetail";
};
CocklainStruct.TUserDetail._classname = "CocklainStruct.TUserDetail";

CocklainStruct.TUserDetail._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TUserDetail._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TUserDetail._readFrom = function (is) {
    var tmp = new CocklainStruct.TUserDetail();
    tmp.bBanker = is.readBoolean(0, true, true);
    tmp.uiSnatchbankerMutiple = is.readUInt32(1, true, 0);
    tmp.uiBaseScore = is.readUInt32(2, true, 0);
    tmp.iRemainScore = is.readInt32(3, true, 0);
    return tmp;
};
CocklainStruct.TUserDetail.prototype._writeTo = function (os) {
    os.writeBoolean(0, this.bBanker);
    os.writeUInt32(1, this.uiSnatchbankerMutiple);
    os.writeUInt32(2, this.uiBaseScore);
    os.writeInt32(3, this.iRemainScore);
};
CocklainStruct.TUserDetail.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TUserDetail.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TUserDetail.prototype.toObject = function() { 
    var tmp = {};

    tmp.bBanker = this.bBanker;
    tmp.uiSnatchbankerMutiple = this.uiSnatchbankerMutiple;
    tmp.uiBaseScore = this.uiBaseScore;
    tmp.iRemainScore = this.iRemainScore;
    
    return tmp;
}
CocklainStruct.TUserDetail.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("bBanker") || (this.bBanker = json.bBanker);
    !json.hasOwnProperty("uiSnatchbankerMutiple") || (this.uiSnatchbankerMutiple = json.uiSnatchbankerMutiple);
    !json.hasOwnProperty("uiBaseScore") || (this.uiBaseScore = json.uiBaseScore);
    !json.hasOwnProperty("iRemainScore") || (this.iRemainScore = json.iRemainScore);
}
CocklainStruct.TUserDetail.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TUserDetail.new = function () {
    return new CocklainStruct.TUserDetail();
}
CocklainStruct.TUserDetail.create = function (is) {
    return CocklainStruct.TUserDetail._readFrom(is);
}
CocklainStruct.TMsgCountdownTime = function() {
    this.msg = CocklainStruct.E_SERVER_MSG.SM_SendCard;
    this.uiTime = 0;
    this._classname = "CocklainStruct.TMsgCountdownTime";
};
CocklainStruct.TMsgCountdownTime._classname = "CocklainStruct.TMsgCountdownTime";

CocklainStruct.TMsgCountdownTime._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TMsgCountdownTime._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TMsgCountdownTime._readFrom = function (is) {
    var tmp = new CocklainStruct.TMsgCountdownTime();
    tmp.msg = is.readInt32(0, true, CocklainStruct.E_SERVER_MSG.SM_SendCard);
    tmp.uiTime = is.readUInt32(1, true, 0);
    return tmp;
};
CocklainStruct.TMsgCountdownTime.prototype._writeTo = function (os) {
    os.writeInt32(0, this.msg);
    os.writeUInt32(1, this.uiTime);
};
CocklainStruct.TMsgCountdownTime.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TMsgCountdownTime.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TMsgCountdownTime.prototype.toObject = function() { 
    var tmp = {};

    tmp.msg = this.msg;
    tmp.uiTime = this.uiTime;
    
    return tmp;
}
CocklainStruct.TMsgCountdownTime.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("msg") || (this.msg = json.msg);
    !json.hasOwnProperty("uiTime") || (this.uiTime = json.uiTime);
}
CocklainStruct.TMsgCountdownTime.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TMsgCountdownTime.new = function () {
    return new CocklainStruct.TMsgCountdownTime();
}
CocklainStruct.TMsgCountdownTime.create = function (is) {
    return CocklainStruct.TMsgCountdownTime._readFrom(is);
}
CocklainStruct.TGameData = function() {
    this.vecMsgCountdownTime = new TarsStream.List(CocklainStruct.TMsgCountdownTime);
    this.vecOdds = new TarsStream.List(TarsStream.Int64);
    this.uiCurrRound = 0;
    this.eGameStatus = CocklainStruct.E_GAME_STATUS.GS_SendCard;
    this.uiCurrCountdownTime = 0;
    this.vecUserDetail = new TarsStream.List(CocklainStruct.TUserDetail);
    this.sendCardData = new CocklainStruct.TSendCardData();
    this.baseScoreConf = new CocklainStruct.TBaseScoreConf();
    this.scoreSellBuyConf = new CocklainStruct.TScoreSellBuyConf();
    this.scoreSellBuyRecord = new CocklainStruct.TScoreSellBuyRecord();
    this.roundResult = new CocklainStruct.TRoundResult();
    this.uiChairIndex = 0;
    this._classname = "CocklainStruct.TGameData";
};
CocklainStruct.TGameData._classname = "CocklainStruct.TGameData";

CocklainStruct.TGameData._write = function (os, tag, value) { os.writeStruct(tag, value); }
CocklainStruct.TGameData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
CocklainStruct.TGameData._readFrom = function (is) {
    var tmp = new CocklainStruct.TGameData();
    tmp.vecMsgCountdownTime = is.readList(0, true, TarsStream.List(CocklainStruct.TMsgCountdownTime));
    tmp.vecOdds = is.readList(1, true, TarsStream.List(TarsStream.Int64));
    tmp.uiCurrRound = is.readUInt32(2, true, 0);
    tmp.eGameStatus = is.readInt32(3, true, CocklainStruct.E_GAME_STATUS.GS_SendCard);
    tmp.uiCurrCountdownTime = is.readUInt32(4, true, 0);
    tmp.vecUserDetail = is.readList(5, true, TarsStream.List(CocklainStruct.TUserDetail));
    tmp.sendCardData = is.readStruct(6, false, CocklainStruct.TSendCardData);
    tmp.baseScoreConf = is.readStruct(7, false, CocklainStruct.TBaseScoreConf);
    tmp.scoreSellBuyConf = is.readStruct(8, false, CocklainStruct.TScoreSellBuyConf);
    tmp.scoreSellBuyRecord = is.readStruct(9, false, CocklainStruct.TScoreSellBuyRecord);
    tmp.roundResult = is.readStruct(10, true, CocklainStruct.TRoundResult);
    tmp.uiChairIndex = is.readUInt32(11, true, 0);
    return tmp;
};
CocklainStruct.TGameData.prototype._writeTo = function (os) {
    os.writeList(0, this.vecMsgCountdownTime);
    os.writeList(1, this.vecOdds);
    os.writeUInt32(2, this.uiCurrRound);
    os.writeInt32(3, this.eGameStatus);
    os.writeUInt32(4, this.uiCurrCountdownTime);
    os.writeList(5, this.vecUserDetail);
    os.writeStruct(6, this.sendCardData);
    os.writeStruct(7, this.baseScoreConf);
    os.writeStruct(8, this.scoreSellBuyConf);
    os.writeStruct(9, this.scoreSellBuyRecord);
    os.writeStruct(10, this.roundResult);
    os.writeUInt32(11, this.uiChairIndex);
};
CocklainStruct.TGameData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
CocklainStruct.TGameData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
CocklainStruct.TGameData.prototype.toObject = function() { 
    var tmp = {};

    tmp.vecMsgCountdownTime = this.vecMsgCountdownTime.toObject();
    tmp.vecOdds = this.vecOdds.toObject();
    tmp.uiCurrRound = this.uiCurrRound;
    tmp.eGameStatus = this.eGameStatus;
    tmp.uiCurrCountdownTime = this.uiCurrCountdownTime;
    tmp.vecUserDetail = this.vecUserDetail.toObject();
    tmp.sendCardData = this.sendCardData.toObject();
    tmp.baseScoreConf = this.baseScoreConf.toObject();
    tmp.scoreSellBuyConf = this.scoreSellBuyConf.toObject();
    tmp.scoreSellBuyRecord = this.scoreSellBuyRecord.toObject();
    tmp.roundResult = this.roundResult.toObject();
    tmp.uiChairIndex = this.uiChairIndex;
    
    return tmp;
}
CocklainStruct.TGameData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vecMsgCountdownTime") || (this.vecMsgCountdownTime.readFromObject(json.vecMsgCountdownTime));
    !json.hasOwnProperty("vecOdds") || (this.vecOdds.readFromObject(json.vecOdds));
    !json.hasOwnProperty("uiCurrRound") || (this.uiCurrRound = json.uiCurrRound);
    !json.hasOwnProperty("eGameStatus") || (this.eGameStatus = json.eGameStatus);
    !json.hasOwnProperty("uiCurrCountdownTime") || (this.uiCurrCountdownTime = json.uiCurrCountdownTime);
    !json.hasOwnProperty("vecUserDetail") || (this.vecUserDetail.readFromObject(json.vecUserDetail));
    !json.hasOwnProperty("sendCardData") || (this.sendCardData.readFromObject(json.sendCardData));
    !json.hasOwnProperty("baseScoreConf") || (this.baseScoreConf.readFromObject(json.baseScoreConf));
    !json.hasOwnProperty("scoreSellBuyConf") || (this.scoreSellBuyConf.readFromObject(json.scoreSellBuyConf));
    !json.hasOwnProperty("scoreSellBuyRecord") || (this.scoreSellBuyRecord.readFromObject(json.scoreSellBuyRecord));
    !json.hasOwnProperty("roundResult") || (this.roundResult.readFromObject(json.roundResult));
    !json.hasOwnProperty("uiChairIndex") || (this.uiChairIndex = json.uiChairIndex);
}
CocklainStruct.TGameData.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
CocklainStruct.TGameData.new = function () {
    return new CocklainStruct.TGameData();
}
CocklainStruct.TGameData.create = function (is) {
    return CocklainStruct.TGameData._readFrom(is);
}


