// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

var TarsGame = require('./TarsGame.js').TarsGame;
module.exports.TarsGame = TarsGame;

var {handleRoomMessage, handleClientMessage} = require('../game_event/GM_Events.js');

TarsGame.IGameMessageImp.prototype.initialize = function ( ) {
    //TODO::

}

TarsGame.IGameMessageImp.prototype.doRoomMessage = function (current, tReqMessage, tRespMessage) {
    handleRoomMessage(current, tReqMessage, tRespMessage);
}

TarsGame.IGameMessageImp.prototype.doClientMessage = function (current, tReqMessage, tRespMessage) {
    handleClientMessage(current, tReqMessage, tRespMessage);
}
