// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

"use strict";

var assert     = require('assert');
var TarsStream = require('@tars/stream');
var TarsError  = require('@tars/rpc').error;

var TarsGame = TarsGame || {};
module.exports.TarsGame = TarsGame;


TarsGame.E_GAME_MSGID = {
    GAMECREATE : 11,
    GAMESTART : 12,
    GAMETIMEOUT : 13,
    GAMEFINISH : 14,
    GAMEOVER : 15,
    GAMEDISMISS : 16,
    GAMERESULT : 17,
    GAMEACTION : 18
};
TarsGame.E_GAME_MSGID._write = function(os, tag, val) { return os.writeInt32(tag, val); }
TarsGame.E_GAME_MSGID._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

TarsGame.EGameMsgType = {
    E_NOTIFY_DATA : 0,
    E_RESPONE_DATA : 1,
    E_RESPALL_DATA : 2,
    E_MIXTURE_DATA : 3,
    E_NONE_DATA : 10
};
TarsGame.EGameMsgType._write = function(os, tag, val) { return os.writeInt32(tag, val); }
TarsGame.EGameMsgType._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

TarsGame.TGameCreate = function() {
    this.roomType = 0;
    this.rules = "";
    this._classname = "TarsGame.TGameCreate";
};
TarsGame.TGameCreate._classname = "TarsGame.TGameCreate";

TarsGame.TGameCreate._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TGameCreate._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TGameCreate._readFrom = function (is) {
    var tmp = new TarsGame.TGameCreate();
    tmp.roomType = is.readInt8(0, true, 0);
    tmp.rules = is.readString(10, true, "");
    return tmp;
};
TarsGame.TGameCreate.prototype._writeTo = function (os) {
    os.writeInt8(0, this.roomType);
    os.writeString(10, this.rules);
};
TarsGame.TGameCreate.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TGameCreate.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TGameCreate.prototype.toObject = function() { 
    var tmp = {};

    tmp.roomType = this.roomType;
    tmp.rules = this.rules;
    
    return tmp;
}
TarsGame.TGameCreate.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("roomType") || (this.roomType = json.roomType);
    !json.hasOwnProperty("rules") || (this.rules = json.rules);
}
TarsGame.TGameCreate.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TGameCreate.new = function () {
    return new TarsGame.TGameCreate();
}
TarsGame.TGameCreate.create = function (is) {
    return TarsGame.TGameCreate._readFrom(is);
}

TarsGame.TPlayerInfo = function() {
    this.userID = 0;
    this.nChairNo = 0;
    this._classname = "TarsGame.TPlayerInfo";
};
TarsGame.TPlayerInfo._classname = "TarsGame.TPlayerInfo";

TarsGame.TPlayerInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TPlayerInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TPlayerInfo._readFrom = function (is) {
    var tmp = new TarsGame.TPlayerInfo();
    tmp.userID = is.readInt64(0, true, 0);
    tmp.nChairNo = is.readInt16(1, true, 0);
    return tmp;
};
TarsGame.TPlayerInfo.prototype._writeTo = function (os) {
    os.writeInt64(0, this.userID);
    os.writeInt16(1, this.nChairNo);
};
TarsGame.TPlayerInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TPlayerInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TPlayerInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.userID = this.userID;
    tmp.nChairNo = this.nChairNo;
    
    return tmp;
}
TarsGame.TPlayerInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("userID") || (this.userID = json.userID);
    !json.hasOwnProperty("nChairNo") || (this.nChairNo = json.nChairNo);
}
TarsGame.TPlayerInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TPlayerInfo.new = function () {
    return new TarsGame.TPlayerInfo();
}
TarsGame.TPlayerInfo.create = function (is) {
    return TarsGame.TPlayerInfo._readFrom(is);
}

TarsGame.TGamgStart = function() {
    this.playerInfo = new TarsStream.List(TarsGame.TPlayerInfo);
    this._classname = "TarsGame.TGamgStart";
};
TarsGame.TGamgStart._classname = "TarsGame.TGamgStart";

TarsGame.TGamgStart._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TGamgStart._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TGamgStart._readFrom = function (is) {
    var tmp = new TarsGame.TGamgStart();
    tmp.playerInfo = is.readList(0, true, TarsStream.List(TarsGame.TPlayerInfo));
    return tmp;
};
TarsGame.TGamgStart.prototype._writeTo = function (os) {
    os.writeList(0, this.playerInfo);
};
TarsGame.TGamgStart.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TGamgStart.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TGamgStart.prototype.toObject = function() { 
    var tmp = {};

    tmp.playerInfo = this.playerInfo.toObject();
    
    return tmp;
}
TarsGame.TGamgStart.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("playerInfo") || (this.playerInfo.readFromObject(json.playerInfo));
}
TarsGame.TGamgStart.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TGamgStart.new = function () {
    return new TarsGame.TGamgStart();
}
TarsGame.TGamgStart.create = function (is) {
    return TarsGame.TGamgStart._readFrom(is);
}

TarsGame.TReqClientMsg = function() {
    this.nMsgID = 0;
    this.vecData = new TarsStream.BinBuffer();
    this._classname = "TarsGame.TReqClientMsg";
};
TarsGame.TReqClientMsg._classname = "TarsGame.TReqClientMsg";

TarsGame.TReqClientMsg._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TReqClientMsg._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TReqClientMsg._readFrom = function (is) {
    var tmp = new TarsGame.TReqClientMsg();
    tmp.nMsgID = is.readInt16(0, true, 0);
    tmp.vecData = is.readBytes(1, true, TarsStream.BinBuffer);
    return tmp;
};
TarsGame.TReqClientMsg.prototype._writeTo = function (os) {
    os.writeInt16(0, this.nMsgID);
    os.writeBytes(1, this.vecData);
};
TarsGame.TReqClientMsg.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TReqClientMsg.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TReqClientMsg.prototype.toObject = function() { 
    var tmp = {};

    tmp.nMsgID = this.nMsgID;
    tmp.vecData = this.vecData.toObject();
    
    return tmp;
}
TarsGame.TReqClientMsg.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("nMsgID") || (this.nMsgID = json.nMsgID);
    !json.hasOwnProperty("vecData") || (this.vecData.readFromObject(json.vecData));
}
TarsGame.TReqClientMsg.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TReqClientMsg.new = function () {
    return new TarsGame.TReqClientMsg();
}
TarsGame.TReqClientMsg.create = function (is) {
    return TarsGame.TReqClientMsg._readFrom(is);
}

TarsGame.TReqRoomMsg = function() {
    this.nVer = 1;
    this.nMsgID = 0;
    this.sTableNo = "";
    this.vecData = new TarsStream.BinBuffer();
    this._classname = "TarsGame.TReqRoomMsg";
};
TarsGame.TReqRoomMsg._classname = "TarsGame.TReqRoomMsg";

TarsGame.TReqRoomMsg._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TReqRoomMsg._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TReqRoomMsg._readFrom = function (is) {
    var tmp = new TarsGame.TReqRoomMsg();
    tmp.nVer = is.readInt16(0, true, 1);
    tmp.nMsgID = is.readInt16(1, true, 0);
    tmp.sTableNo = is.readString(2, true, "");
    tmp.vecData = is.readBytes(3, false, TarsStream.BinBuffer);
    return tmp;
};
TarsGame.TReqRoomMsg.prototype._writeTo = function (os) {
    os.writeInt16(0, this.nVer);
    os.writeInt16(1, this.nMsgID);
    os.writeString(2, this.sTableNo);
    os.writeBytes(3, this.vecData);
};
TarsGame.TReqRoomMsg.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TReqRoomMsg.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TReqRoomMsg.prototype.toObject = function() { 
    var tmp = {};

    tmp.nVer = this.nVer;
    tmp.nMsgID = this.nMsgID;
    tmp.sTableNo = this.sTableNo;
    tmp.vecData = this.vecData.toObject();
    
    return tmp;
}
TarsGame.TReqRoomMsg.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("nVer") || (this.nVer = json.nVer);
    !json.hasOwnProperty("nMsgID") || (this.nMsgID = json.nMsgID);
    !json.hasOwnProperty("sTableNo") || (this.sTableNo = json.sTableNo);
    !json.hasOwnProperty("vecData") || (this.vecData.readFromObject(json.vecData));
}
TarsGame.TReqRoomMsg.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TReqRoomMsg.new = function () {
    return new TarsGame.TReqRoomMsg();
}
TarsGame.TReqRoomMsg.create = function (is) {
    return TarsGame.TReqRoomMsg._readFrom(is);
}

TarsGame.TReqRoomTranspondMsg = function() {
    this.nMsgID = 0;
    this.sTableNo = "";
    this.nChairIdx = 0;
    this.vecData = new TarsStream.BinBuffer();
    this._classname = "TarsGame.TReqRoomTranspondMsg";
};
TarsGame.TReqRoomTranspondMsg._classname = "TarsGame.TReqRoomTranspondMsg";

TarsGame.TReqRoomTranspondMsg._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TReqRoomTranspondMsg._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TReqRoomTranspondMsg._readFrom = function (is) {
    var tmp = new TarsGame.TReqRoomTranspondMsg();
    tmp.nMsgID = is.readInt16(1, true, 0);
    tmp.sTableNo = is.readString(2, true, "");
    tmp.nChairIdx = is.readInt16(3, true, 0);
    tmp.vecData = is.readBytes(4, false, TarsStream.BinBuffer);
    return tmp;
};
TarsGame.TReqRoomTranspondMsg.prototype._writeTo = function (os) {
    os.writeInt16(1, this.nMsgID);
    os.writeString(2, this.sTableNo);
    os.writeInt16(3, this.nChairIdx);
    os.writeBytes(4, this.vecData);
};
TarsGame.TReqRoomTranspondMsg.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TReqRoomTranspondMsg.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TReqRoomTranspondMsg.prototype.toObject = function() { 
    var tmp = {};

    tmp.nMsgID = this.nMsgID;
    tmp.sTableNo = this.sTableNo;
    tmp.nChairIdx = this.nChairIdx;
    tmp.vecData = this.vecData.toObject();
    
    return tmp;
}
TarsGame.TReqRoomTranspondMsg.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("nMsgID") || (this.nMsgID = json.nMsgID);
    !json.hasOwnProperty("sTableNo") || (this.sTableNo = json.sTableNo);
    !json.hasOwnProperty("nChairIdx") || (this.nChairIdx = json.nChairIdx);
    !json.hasOwnProperty("vecData") || (this.vecData.readFromObject(json.vecData));
}
TarsGame.TReqRoomTranspondMsg.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TReqRoomTranspondMsg.new = function () {
    return new TarsGame.TReqRoomTranspondMsg();
}
TarsGame.TReqRoomTranspondMsg.create = function (is) {
    return TarsGame.TReqRoomTranspondMsg._readFrom(is);
}

TarsGame.TData = function() {
    this.nMsgID = 0;
    this.vecData = new TarsStream.BinBuffer();
    this._classname = "TarsGame.TData";
};
TarsGame.TData._classname = "TarsGame.TData";

TarsGame.TData._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TData._readFrom = function (is) {
    var tmp = new TarsGame.TData();
    tmp.nMsgID = is.readInt16(0, true, 0);
    tmp.vecData = is.readBytes(1, true, TarsStream.BinBuffer);
    return tmp;
};
TarsGame.TData.prototype._writeTo = function (os) {
    os.writeInt16(0, this.nMsgID);
    os.writeBytes(1, this.vecData);
};
TarsGame.TData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TData.prototype.toObject = function() { 
    var tmp = {};

    tmp.nMsgID = this.nMsgID;
    tmp.vecData = this.vecData.toObject();
    
    return tmp;
}
TarsGame.TData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("nMsgID") || (this.nMsgID = json.nMsgID);
    !json.hasOwnProperty("vecData") || (this.vecData.readFromObject(json.vecData));
}
TarsGame.TData.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TData.new = function () {
    return new TarsGame.TData();
}
TarsGame.TData.create = function (is) {
    return TarsGame.TData._readFrom(is);
}

TarsGame.TGameData = function() {
    this.tRespOneData = new TarsGame.TData();
    this.tNotifyData = new TarsGame.TData();
    this.tNotifyOnlookerData = new TarsGame.TData();
    this.vecRespAllData = new TarsStream.List(TarsGame.TData);
    this._classname = "TarsGame.TGameData";
};
TarsGame.TGameData._classname = "TarsGame.TGameData";

TarsGame.TGameData._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TGameData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TGameData._readFrom = function (is) {
    var tmp = new TarsGame.TGameData();
    tmp.tRespOneData = is.readStruct(0, false, TarsGame.TData);
    tmp.tNotifyData = is.readStruct(1, false, TarsGame.TData);
    tmp.tNotifyOnlookerData = is.readStruct(2, false, TarsGame.TData);
    tmp.vecRespAllData = is.readList(3, false, TarsStream.List(TarsGame.TData));
    return tmp;
};
TarsGame.TGameData.prototype._writeTo = function (os) {
    os.writeStruct(0, this.tRespOneData);
    os.writeStruct(1, this.tNotifyData);
    os.writeStruct(2, this.tNotifyOnlookerData);
    os.writeList(3, this.vecRespAllData);
};
TarsGame.TGameData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TGameData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TGameData.prototype.toObject = function() { 
    var tmp = {};

    tmp.tRespOneData = this.tRespOneData.toObject();
    tmp.tNotifyData = this.tNotifyData.toObject();
    tmp.tNotifyOnlookerData = this.tNotifyOnlookerData.toObject();
    tmp.vecRespAllData = this.vecRespAllData.toObject();
    
    return tmp;
}
TarsGame.TGameData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("tRespOneData") || (this.tRespOneData.readFromObject(json.tRespOneData));
    !json.hasOwnProperty("tNotifyData") || (this.tNotifyData.readFromObject(json.tNotifyData));
    !json.hasOwnProperty("tNotifyOnlookerData") || (this.tNotifyOnlookerData.readFromObject(json.tNotifyOnlookerData));
    !json.hasOwnProperty("vecRespAllData") || (this.vecRespAllData.readFromObject(json.vecRespAllData));
}
TarsGame.TGameData.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TGameData.new = function () {
    return new TarsGame.TGameData();
}
TarsGame.TGameData.create = function (is) {
    return TarsGame.TGameData._readFrom(is);
}

TarsGame.TRespMessage = function() {
    this.nTimeout = 0;
    this.eMsgType = TarsGame.EGameMsgType.E_NOTIFY_DATA;
    this.tGameData = new TarsGame.TGameData();
    this._classname = "TarsGame.TRespMessage";
};
TarsGame.TRespMessage._classname = "TarsGame.TRespMessage";

TarsGame.TRespMessage._write = function (os, tag, value) { os.writeStruct(tag, value); }
TarsGame.TRespMessage._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
TarsGame.TRespMessage._readFrom = function (is) {
    var tmp = new TarsGame.TRespMessage();
    tmp.nTimeout = is.readInt16(0, true, 0);
    tmp.eMsgType = is.readInt32(1, true, TarsGame.EGameMsgType.E_NOTIFY_DATA);
    tmp.tGameData = is.readStruct(2, true, TarsGame.TGameData);
    return tmp;
};
TarsGame.TRespMessage.prototype._writeTo = function (os) {
    os.writeInt16(0, this.nTimeout);
    os.writeInt32(1, this.eMsgType);
    os.writeStruct(2, this.tGameData);
};
TarsGame.TRespMessage.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
TarsGame.TRespMessage.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
TarsGame.TRespMessage.prototype.toObject = function() { 
    var tmp = {};

    tmp.nTimeout = this.nTimeout;
    tmp.eMsgType = this.eMsgType;
    tmp.tGameData = this.tGameData.toObject();
    
    return tmp;
}
TarsGame.TRespMessage.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("nTimeout") || (this.nTimeout = json.nTimeout);
    !json.hasOwnProperty("eMsgType") || (this.eMsgType = json.eMsgType);
    !json.hasOwnProperty("tGameData") || (this.tGameData.readFromObject(json.tGameData));
}
TarsGame.TRespMessage.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
TarsGame.TRespMessage.new = function () {
    return new TarsGame.TRespMessage();
}
TarsGame.TRespMessage.create = function (is) {
    return TarsGame.TRespMessage._readFrom(is);
}

TarsGame.IGameMessageImp = function () { 
    this._name   = undefined;
    this._worker = undefined;
}

TarsGame.IGameMessageImp.prototype.initialize = function () { 
    //TODO:
}

TarsGame.IGameMessageImp.prototype.onDispatch = function (current, FuncName, BinBuffer) { 
    switch (FuncName) {
        case 'tars_ping': {
                current.sendResponse = function (_ret) {
                        if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX){
                                var tup = new TarsStream.UniAttribute();
                                tup.tupVersion = current.getRequestVersion();
                                tup.writeInt32("", _ret);
                                current.doResponse(tup.encode());
                        }else{
                                var os = new TarsStream.TarsOutputStream();
                                os.writeInt32(0, _ret);
                                current.doResponse(os.getBinBuffer());
                        }
                }
                        current.sendResponse(0);
                return TarsError.SUCCESS;
        }
        case 'doRoomMessage' : {
            if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                var tup = new TarsStream.UniAttribute();
                tup.tupVersion = current.getRequestVersion();
                tup.decode(BinBuffer);
                var tReqRoomMsg = tup.readStruct("tReqRoomMsg", TarsGame.TReqRoomMsg);
                var tRespMessage = tup.readStruct("tRespMessage", TarsGame.TRespMessage, new TarsGame.TRespMessage());
            } else {
                var is = new TarsStream.TarsInputStream(BinBuffer);
                var tReqRoomMsg = is.readStruct(1, true, TarsGame.TReqRoomMsg);
                var tRespMessage = is.readStruct(2, false, TarsGame.TRespMessage);
            }
            current.sendResponse = function (_ret, tRespMessage) {
                if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                    var tup = new TarsStream.UniAttribute();
                    tup.tupVersion = current.getRequestVersion();
                    tup.writeInt16("", _ret);
                    tup.writeStruct("tRespMessage", tRespMessage);

                    current.doResponse(tup.encode());
                } else {
                    var os = new TarsStream.TarsOutputStream();
                    os.writeInt16(0, _ret);
                    os.writeStruct(2, tRespMessage);

                    current.doResponse(os.getBinBuffer());
                }
            }

            this.doRoomMessage(current, tReqRoomMsg, tRespMessage);

            return TarsError.SUCCESS;
        }
        case 'doClientMessage' : {
            if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                var tup = new TarsStream.UniAttribute();
                tup.tupVersion = current.getRequestVersion();
                tup.decode(BinBuffer);
                var tReqRoomTranspondMsg = tup.readStruct("tReqRoomTranspondMsg", TarsGame.TReqRoomTranspondMsg);
                var tRespMessage = tup.readStruct("tRespMessage", TarsGame.TRespMessage, new TarsGame.TRespMessage());
            } else {
                var is = new TarsStream.TarsInputStream(BinBuffer);
                var tReqRoomTranspondMsg = is.readStruct(1, true, TarsGame.TReqRoomTranspondMsg);
                var tRespMessage = is.readStruct(2, false, TarsGame.TRespMessage);
            }
            current.sendResponse = function (_ret, tRespMessage) {
                if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                    var tup = new TarsStream.UniAttribute();
                    tup.tupVersion = current.getRequestVersion();
                    tup.writeInt16("", _ret);
                    tup.writeStruct("tRespMessage", tRespMessage);

                    current.doResponse(tup.encode());
                } else {
                    var os = new TarsStream.TarsOutputStream();
                    os.writeInt16(0, _ret);
                    os.writeStruct(2, tRespMessage);

                    current.doResponse(os.getBinBuffer());
                }
            }

            this.doClientMessage(current, tReqRoomTranspondMsg, tRespMessage);

            return TarsError.SUCCESS;
        }
    }
    return TarsError.SERVER.FUNC_NOT_FOUND;
}

TarsGame.IGameMessageImp.prototype.doRoomMessage = function (current, tReqRoomMsg, tRespMessage) {
    //TODO:
    assert.fail('doRoomMessage function not implemented');
}

TarsGame.IGameMessageImp.prototype.doClientMessage = function (current, tReqRoomTranspondMsg, tRespMessage) {
    //TODO:
    assert.fail('doClientMessage function not implemented');
}





